### ISSUE TITLE
Partner with us bubbles overlap email us button on tablet view

### ISSUE THREAD

**Issue by yxxko** [AIGAdc/dcdesignweek.org#282]
**Describe the bug**
Partner with us bubbles overlap email us button on tablet view
![IMG-0047](https://user-images.githubusercontent.com/50876600/87366361-86501800-c546-11ea-9869-2137d7c39973.PNG)

-   OS: iOS
-   Safari

**Comment by marcusrelacion** [comment]
Fixed in https://github.com/AIGAdc/dcdesignweek.org/commit/0a5b2c2d9f651e3f2757629d430ceec9809256b9
