### ISSUE TITLE
Rounded Form Fields and Subscribe button

### ISSUE THREAD

**Issue by yxxko** [AIGAdc/dcdesignweek.org#283]
**Describe the bug**
Rounded form fields and subscribe button iOS, Safari
![IMG-0048](https://user-images.githubusercontent.com/50876600/87366462-bc8d9780-c546-11ea-8aa9-935b990092e4.PNG)

-   OS: iOS
-  Safari

**Comment by marcusrelacion** [comment]
This was fixed #319
