### ISSUE TITLE
Bubble image needed

### ISSUE THREAD

**Issue by yxxko** [AIGAdc/dcdesignweek.org#284]
**Describe the bug**
There is an area missing a bubble image.

![IMG-0049](https://user-images.githubusercontent.com/50876600/87366535-ee066300-c546-11ea-9eac-cf4cdafc5853.PNG)

iOS, Safari

**Comment by marcusrelacion** [comment]
Fixed in https://github.com/AIGAdc/dcdesignweek.org/commit/d8808ce3afbb075422a9d6fdb11461c4cefd26a3
