### ISSUE TITLE
Side scrolling in portrait and landscape

### ISSUE THREAD

**Issue by yxxko** [AIGAdc/dcdesignweek.org#285]
**Describe the bug**
When scrolling on portrait or landscape on tablet, the page is side scrolling due to a bubble image

**To Reproduce**
Scroll wildly on ipad

**Expected behavior**
should not side scroll

![](https://cdn.discordapp.com/attachments/696731067411070996/732393989990383726/image.png)

![](https://cdn.discordapp.com/attachments/696731067411070996/732394264905908334/image.png)

iOS, Safari

**Comment by marcusrelacion** [comment]
Fixed in https://github.com/AIGAdc/dcdesignweek.org/commit/0a5b2c2d9f651e3f2757629d430ceec9809256b9
