### ISSUE TITLE
Dave Ellington's portrait is missing

### ISSUE THREAD

**Issue by yxxko** [AIGAdc/dcdesignweek.org#287]
**Describe the bug**
Portrait image is broken

![image](https://user-images.githubusercontent.com/50876600/87490287-5589e480-c613-11ea-87a6-954932d8c47e.png)

**Comment by marcusrelacion** [comment]
Fixed in https://github.com/AIGAdc/dcdesignweek.org/pull/275/commits/3b3e3d639502c6a71da515940463d834a0e0e5ac
