### ISSUE TITLE
Navigation Alignment

### ISSUE THREAD

**Issue by silviascript** [AIGAdc/dcdesignweek.org#347]
The navigation (previous years) is not aligned towards the center since it balancing with the logo and button. This is a visual design change as well.

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTRiNDc5ZjMtZWM2YS00ZDBiLWI5NGUtNmZlZmUzMzc4NWUzIiwiZGVwbG95X2lkIjoiNjBiODI5ZjRmN2M3NzUwMDA3ZTdlYTc3IiwiaWQiOiI1YWJjMzg1Ni1jZGI1LTQwZWItOTJjMS1lYjk4Y2FlMWZkMDYifQ==)

```
Path:      /
Browser:   Chrome 90.0.4430.212 on Mac OS 10.15.7
Viewport:  1920 x 1031 @2x
Language:  en-US
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-345--dcdesignweek.netlify.app%2F&os=OS+X&os_version=Catalina&browser=Chrome&browser_version=90.0&resolution=1920x1031&speed=1&start=true)

Submitted from [Netlify Deploy Preview #345](https://deploy-preview-345--dcdesignweek.netlify.app/)

**Comment by yxxko** [comment]
We decided to align the navigation to the middle to give the "Become a Partner" button more breathing room. The balance felt off because the button was heavier this year with the red and black.

**Comment by silviascript** [comment]
The center alignment is a consistent structure throughout the page. This navigation items disrupt that cohesiveness and convey an styling error. If we don't change this now, let's continue the conversation when creating the main website design.
