### ISSUE TITLE
Label Alignment

### ISSUE THREAD

**Issue by silviascript** [AIGAdc/dcdesignweek.org#350]
The spacing before the field labels need to be removed. The labels should be aligned with the field.

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTRiNDc5ZjMtZWM2YS00ZDBiLWI5NGUtNmZlZmUzMzc4NWUzIiwiZGVwbG95X2lkIjoiNjBiODI5ZjRmN2M3NzUwMDA3ZTdlYTc3IiwiaWQiOiI0YzBhMjU2MS1lYTE2LTQ2ODMtYjdkMi1kMGJkYWZlNDZlNDYifQ==)

```
Path:      /
Browser:   Chrome 90.0.4430.212 on Mac OS 10.15.7
Viewport:  1920 x 1031 @2x
Language:  en-US
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-345--dcdesignweek.netlify.app%2F&os=OS+X&os_version=Catalina&browser=Chrome&browser_version=90.0&resolution=1920x1031&speed=1&start=true)

Submitted from [Netlify Deploy Preview #345](https://deploy-preview-345--dcdesignweek.netlify.app/)

**Comment by yxxko** [comment]
Just wanted to point out that they are aligned with what's inside the text field. It makes for a cleaner form once it's filled out.

![image](https://user-images.githubusercontent.com/50876600/120676946-90cc1680-c464-11eb-88a7-5cbe8d7ca2b9.png)

**Comment by silviascript** [comment]
I would recommend not doing that. It looks like an error on my end. The label should be left aligned with the field and the padding on the left inside the field should be consistent with your button (16px).
