### ISSUE TITLE
Headings on events page should be logically ordered

### ISSUE THREAD

**Issue by joshkimux** [AIGAdc/dcdesignweek.org#362]
### Description of issue
Each of the filters are a `h3` , which blends them with the event titles.

### Recommendation

1. Add a `h2` "Filter Events" with a screen reader only class
2. Do not make each filter title a `h3`, as they are not starting up new individual sections; they should be OK just as expand/collapse buttons
3. Add a `h2` between filters and the events list called "List of Events" so screen reader users can know where the filters will end and where the list of events will begin.

On headingsMap, the headings would then look like so:

![image](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTRiNDc5ZjMtZWM2YS00ZDBiLWI5NGUtNmZlZmUzMzc4NWUzIiwiZGVwbG95X2lkIjoiNjEwMDgxN2M0YzM5NGMwMDA4YWI4YjMyIiwiaWQiOiI5MmI0NGZmNC05MmE2LTQ2NmMtYmFmOC1jNDU3NzgwOTY3NzkifQ==)

### Steps to reproduce
Use the headingsMap chrome extension to view the headings on the page.

```
Path:      /events/
Browser:   Chrome 91.0.4472.114 on Mac OS 10.15.7
Viewport:  1792 x 1009 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2Fevents%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=91.0&resolution=1792x1009&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #359](https://deploy-preview-359--dcdesignweek.netlify.app/events/)

**Comment by marcusrelacion** [comment]
This has been updated @joshkimux: 

<img width="350" alt="CleanShot 2021-08-11 at 18 00 02@2x" src="https://user-images.githubusercontent.com/6185899/129109162-e9bd9b8a-a768-489c-8293-78ee032a8b05.png">
