### ISSUE TITLE
Email address ID has typo

### ISSUE THREAD

**Issue by joshkimux** [AIGAdc/dcdesignweek.org#365]
### Description of issue
Email address input field's ID is written as "mce-EM`AIL" instead of "mce-EMAIL" which disconnects the label from the input.

### Screenshot
![image](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTRiNDc5ZjMtZWM2YS00ZDBiLWI5NGUtNmZlZmUzMzc4NWUzIiwiZGVwbG95X2lkIjoiNjExMWJhZjg0NTg3N2EwMDA4NmVjNjMxIiwiaWQiOiIyMWI3OWM4ZS05NTczLTQyMzItYTc2Yi0wMGNiZDI0NmI4ODAifQ==)

```
Path:      /
Browser:   Chrome 92.0.4515.131 on Mac OS 10.15.7
Viewport:  887 x 952 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=92.0&resolution=887x952&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #359](https://deploy-preview-359--dcdesignweek.netlify.app/)

**Comment by marcusrelacion** [comment]
This has been updated @joshkimux:

<img width="541" alt="CleanShot 2021-08-11 at 18 04 06@2x" src="https://user-images.githubusercontent.com/6185899/129109539-61df0c77-1aac-451a-b11b-85d9e82491ff.png">
