### ISSUE TITLE
Focus state on events card

### ISSUE THREAD

**Issue by kirstengreen** [AIGAdc/dcdesignweek.org#368]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTRiNDc5ZjMtZWM2YS00ZDBiLWI5NGUtNmZlZmUzMzc4NWUzIiwiZGVwbG95X2lkIjoiNjExNWM4NWYyOTA4YjIwMDA4N2Y5M2FmIiwiaWQiOiI1NTQwZDNkMi0xMmY3LTRmODItYTI4Mi1jYmI3OGIyODVlY2QifQ==)

### Description of issue
Borders are around every element in the card component instead of just around the card component itself

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /events/
Browser:   Firefox 92.0 on Windows 10
Viewport:  1631 x 921 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2Fevents%2F&os=Windows&os_version=10&browser=Firefox&browser_version=92.0&resolution=1631x921&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #359](https://deploy-preview-359--dcdesignweek.netlify.app/events/)

**Comment by marcusrelacion** [comment]
@kirstengreen this has been fixed.
