### ISSUE TITLE
Events Page - Ticket buttons have no space between

### ISSUE THREAD

**Issue by kirstengreen** [AIGAdc/dcdesignweek.org#376]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTRiNDc5ZjMtZWM2YS00ZDBiLWI5NGUtNmZlZmUzMzc4NWUzIiwiZGVwbG95X2lkIjoiNjExNWM4NWYyOTA4YjIwMDA4N2Y5M2FmIiwiaWQiOiJkNTU1OTZiNy04YTgyLTQwOTYtODMwNy1kNjY0MzhlZmViNmQifQ==)

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /events/and8-fitness-dance-cardio-class/
Browser:   Firefox 92.0 on Windows 10
Viewport:  454 x 921 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2Fevents%2Fand8-fitness-dance-cardio-class%2F&os=Windows&os_version=10&browser=Firefox&browser_version=92.0&resolution=454x921&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #359](https://deploy-preview-359--dcdesignweek.netlify.app/events/and8-fitness-dance-cardio-class/)

**Comment by marcusrelacion** [comment]
@kirstengreen this has been fixed.
