### ISSUE TITLE
FAQ contact info spacing is close to the last question

### ISSUE THREAD

**Issue by kirstengreen** [AIGAdc/dcdesignweek.org#378]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTRiNDc5ZjMtZWM2YS00ZDBiLWI5NGUtNmZlZmUzMzc4NWUzIiwiZGVwbG95X2lkIjoiNjExNWM4NWYyOTA4YjIwMDA4N2Y5M2FmIiwiaWQiOiIxNDQ5ZWMyMC0yYTczLTRhYTAtOTM3Zi01ZTNiYzJlNTk1NTgifQ==)

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /faqs/
Browser:   Firefox 92.0 on Windows 10
Viewport:  1324 x 921 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2Ffaqs%2F&os=Windows&os_version=10&browser=Firefox&browser_version=92.0&resolution=1324x921&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #359](https://deploy-preview-359--dcdesignweek.netlify.app/faqs/)

**Comment by kirstengreen** [comment]
This text actually disappears in larger sizes

**Comment by kirstengreen** [comment]
![image](https://user-images.githubusercontent.com/10482373/129410364-28ac1268-1373-408d-9783-8fcbab40d3d7.png)

**Comment by kirstengreen** [comment]
Disregard the previous comment, missed that it is an aside on larger screens

**Comment by marcusrelacion** [comment]
@kirstengreen this has been fixed.
