### ISSUE TITLE
Sponsors Elements

### ISSUE THREAD

**Issue by silviascript** [AIGAdc/dcdesignweek.org#385]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTRiNDc5ZjMtZWM2YS00ZDBiLWI5NGUtNmZlZmUzMzc4NWUzIiwiZGVwbG95X2lkIjoiNjExNmU4Y2Q5ODU4MGMwMDA3ZTU4YTkzIiwiaWQiOiJiNGQ2Y2Q3MC1hMTY2LTRmZGUtYjBhZS1mOGUzMjdjOTU2NTQifQ==)

There are missing elements in this section. There should be the yellow sticker between the section at the top and an icon on the right side of the logos. Ensure the abstract element with the title is above the grey abstract element.

```
Path:      /
Browser:   Chrome 92.0.4515.131 on Mac OS 10.15.7
Viewport:  1920 x 1032 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=92.0&resolution=1920x1032&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #359](https://deploy-preview-359--dcdesignweek.netlify.app/)

**Comment by silviascript** [comment]
There is also a missing sticker that should be in the top middle between the two sections.

**Comment by silviascript** [comment]
@marcusrelacion, this also applies to the about page as well with the missing icons and layering ordering.

**Comment by marcusrelacion** [comment]
@silviascript this has been fixed.
