### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by silviascript** [AIGAdc/dcdesignweek.org#386]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTRiNDc5ZjMtZWM2YS00ZDBiLWI5NGUtNmZlZmUzMzc4NWUzIiwiZGVwbG95X2lkIjoiNjExNmU4Y2Q5ODU4MGMwMDA3ZTU4YTkzIiwiaWQiOiI2M2U1NjQ2MC0yNmE0LTQ5ODAtOGMxMy1hNDEzN2M3ZDRmZDAifQ==)

The background image was added at one stage and seemed to be working. Re-add images and if this is not feasible, we'll need a design solution.

```
Path:      /
Browser:   Chrome 92.0.4515.131 on Mac OS 10.15.7
Viewport:  1920 x 1032 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=92.0&resolution=1920x1032&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #359](https://deploy-preview-359--dcdesignweek.netlify.app/)

**Comment by silviascript** [comment]
@yxxko, what are your thoughts about adding noise (through) to help give texture to the background if we're not able to the paper?

**Comment by marcusrelacion** [comment]
@silviascript this has been fixed and will be live on my next push.
