### ISSUE TITLE
Hero Elements

### ISSUE THREAD

**Issue by silviascript** [AIGAdc/dcdesignweek.org#388]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTRiNDc5ZjMtZWM2YS00ZDBiLWI5NGUtNmZlZmUzMzc4NWUzIiwiZGVwbG95X2lkIjoiNjExNmU4Y2Q5ODU4MGMwMDA3ZTU4YTkzIiwiaWQiOiJhM2M5YmM3MS0zZjkwLTQ4OGMtYTc0NC1hNTljNTQ3ZGY1ZmIifQ==)

The header font-size needs to be Bayard at 176px. The red abstract should behind the header instead of the black background. There is a missing image that should be placed to the right.

```
Path:      /events/
Browser:   Chrome 92.0.4515.131 on Mac OS 10.15.7
Viewport:  1920 x 1032 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2Fevents%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=92.0&resolution=1920x1032&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #359](https://deploy-preview-359--dcdesignweek.netlify.app/events/)

**Comment by marcusrelacion** [comment]
@silviascript this has been fixed and will be updated in the next push.

**Comment by silviascript** [comment]
@marcusrelacion, this also applies to the FAQs page. I assume this is global so these changes will take affect on the other header. Thanks!
