### ISSUE TITLE
Events Section

### ISSUE THREAD

**Issue by silviascript** [AIGAdc/dcdesignweek.org#389]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTRiNDc5ZjMtZWM2YS00ZDBiLWI5NGUtNmZlZmUzMzc4NWUzIiwiZGVwbG95X2lkIjoiNjExNmU4Y2Q5ODU4MGMwMDA3ZTU4YTkzIiwiaWQiOiJjNGRhZWE3Mi03ZWE0LTRjZjEtYTExZS00NzBkMzY4MTE0YjUifQ==)

There should be more spacing between the filter and events – roughly 60px. The line-heights for the date and time needs to be tighter. The sticker needs to be replaced. Update the spacing below the event images.

```
Path:      /events/
Browser:   Chrome 92.0.4515.131 on Mac OS 10.15.7
Viewport:  1920 x 1032 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2Fevents%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=92.0&resolution=1920x1032&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #359](https://deploy-preview-359--dcdesignweek.netlify.app/events/)

**Comment by marcusrelacion** [comment]
@silviascript this has been fixed.
