### ISSUE TITLE
Staff Section

### ISSUE THREAD

**Issue by silviascript** [AIGAdc/dcdesignweek.org#392]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTRiNDc5ZjMtZWM2YS00ZDBiLWI5NGUtNmZlZmUzMzc4NWUzIiwiZGVwbG95X2lkIjoiNjExNmU4Y2Q5ODU4MGMwMDA3ZTU4YTkzIiwiaWQiOiJhMWU2OWRlMi03N2Q0LTRjMTgtOGEyZS1iM2E2OWU5NjU4MjUifQ==)

The staff needs more padding above the header. The headshots needs to scale down to match the current designs. The name and position needs to be 16px, while the header is bold. Check Figma for correct spacing.

```
Path:      /about/
Browser:   Chrome 92.0.4515.131 on Mac OS 10.15.7
Viewport:  1920 x 1032 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2Fabout%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=92.0&resolution=1920x1032&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #359](https://deploy-preview-359--dcdesignweek.netlify.app/about/)

**Comment by marcusrelacion** [comment]
@silviascript this has been fixed. Will address the padding of the section in another update.
