### ISSUE TITLE
FAQs Styling

### ISSUE THREAD

**Issue by silviascript** [AIGAdc/dcdesignweek.org#395]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTRiNDc5ZjMtZWM2YS00ZDBiLWI5NGUtNmZlZmUzMzc4NWUzIiwiZGVwbG95X2lkIjoiNjExNmU4Y2Q5ODU4MGMwMDA3ZTU4YTkzIiwiaWQiOiJmMjZhNDkxZC0wOGFhLTRiMzktOGViNS0xY2MxMmI4ZDY0OGUifQ==)

The spacing between the accordions and questions should be similar to the the filters and events. The question headers should be bold.

```
Path:      /faqs/
Browser:   Chrome 92.0.4515.131 on Mac OS 10.15.7
Viewport:  1920 x 1032 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2Ffaqs%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=92.0&resolution=1920x1032&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #359](https://deploy-preview-359--dcdesignweek.netlify.app/faqs/)

**Comment by marcusrelacion** [comment]
@silviascript this has been fixed and will be updated in my next update.
