### ISSUE TITLE
Hero Styling

### ISSUE THREAD

**Issue by silviascript** [AIGAdc/dcdesignweek.org#397]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTRiNDc5ZjMtZWM2YS00ZDBiLWI5NGUtNmZlZmUzMzc4NWUzIiwiZGVwbG95X2lkIjoiNjExN2YxYWM0NGU2MDgwMDA4N2IzNGMzIiwiaWQiOiJiNDE5MWZiZC0zYzdhLTQyNDItYjI5MS1iNzI4MTNiNWMyYzQifQ==)

Let's decrease the height to accommodate the amount of content. Maybe try 80px to see if that helps? Also, the content should be bolder under the hero elements.

```
Path:      /
Browser:   Chrome 92.0.4515.131 on Mac OS 10.15.7
Viewport:  1920 x 1064 @1x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=92.0&resolution=1920x1064&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #359](https://deploy-preview-359--dcdesignweek.netlify.app/)

**Comment by silviascript** [comment]
@marcusrelacion, the spacing may need to be 80px for all sections judging by the other sections. Will need to see a comparison.

**Comment by marcusrelacion** [comment]
@silviascript the bolding has been fixed and I will work on the padding after updating the site content.
