### ISSUE TITLE
Hero Event Styling

### ISSUE THREAD

**Issue by silviascript** [AIGAdc/dcdesignweek.org#399]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTRiNDc5ZjMtZWM2YS00ZDBiLWI5NGUtNmZlZmUzMzc4NWUzIiwiZGVwbG95X2lkIjoiNjExN2YxYWM0NGU2MDgwMDA4N2IzNGMzIiwiaWQiOiJiYzViMWNhNC05NTBlLTQ0NTAtYmUxMS1kYTAyOTAyZDgzNzIifQ==)

The hero needs to the use Bayard font for the event name. There should be more spacing between the "/" and the two buttons. I assume we can't change the second button to a border since both are equal.

```
Path:      /events/and8-fitness-dance-cardio-class/
Browser:   Chrome 92.0.4515.131 on Mac OS 10.15.7
Viewport:  1920 x 1064 @1x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2Fevents%2Fand8-fitness-dance-cardio-class%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=92.0&resolution=1920x1064&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #359](https://deploy-preview-359--dcdesignweek.netlify.app/events/and8-fitness-dance-cardio-class/)

**Comment by marcusrelacion** [comment]
@silviascript this has been fixed. Will address the button spacing in the next update.
