### ISSUE TITLE
Chita Rivera Header

### ISSUE THREAD

**Issue by yxxko** [AIGAdc/dcdesignweek.org#402]
### Description of issue
Chita Rivera header isn’t inside the shape. Shape could get larger to encompass the entire header

### Steps to reproduce
1. Go to the homepage on mobile in safari

```
Path:      /
Browser:   Mobile Safari 14.1.1 on iOS 14.6
Viewport:  428 x 860 @3x
Language:  en-us
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2F&os=iOS&os_version=14.6&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #359](https://deploy-preview-359--dcdesignweek.netlify.app/)

**Comment by marcusrelacion** [comment]
@yxxko this has been fixed.
