### ISSUE TITLE
Larger H1s on mobile

### ISSUE THREAD

**Issue by yxxko** [AIGAdc/dcdesignweek.org#404]
### Description of issue
Can we up the size of the h1s on mobile so they are at least larger than the H2s. This is creating a little bit of a strange hierarchy

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /about/
Browser:   Mobile Safari 14.1.1 on iOS 14.6
Viewport:  428 x 746 @3x
Language:  en-us
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2Fabout%2F&os=iOS&os_version=14.6&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #359](https://deploy-preview-359--dcdesignweek.netlify.app/about/)

**Comment by marcusrelacion** [comment]
@yxxko this has been fixed.
