### ISSUE TITLE
Date on the event cards is up against the left edge of the screen

### ISSUE THREAD

**Issue by yxxko** [AIGAdc/dcdesignweek.org#405]
### Description of issue
The events card date shape is up against the edge of the screen. Maybe the margin needs to be adjusted?

### Steps to reproduce
1. Go to the events page on mobile
2. Scroll down the the evens cards

```
Path:      /events/
Browser:   Mobile Safari 14.1.1 on iOS 14.6
Viewport:  428 x 860 @3x
Language:  en-us
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2Fevents%2F&os=iOS&os_version=14.6&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #359](https://deploy-preview-359--dcdesignweek.netlify.app/events/)

**Comment by marcusrelacion** [comment]
@yxxko this has been fixed.
