### ISSUE TITLE
Styling issue on speaker about in individual event page

### ISSUE THREAD

**Issue by yxxko** [AIGAdc/dcdesignweek.org#406]
### Description of issue
Speaker bio should be red not black. It’s also missing the line under the about title.

### Actual result

https://deploy-preview-359--dcdesignweek.netlify.app/events/and8-fitness-dance-cardio-class/

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /events/and8-fitness-dance-cardio-class/
Browser:   Mobile Safari 14.1.1 on iOS 14.6
Viewport:  428 x 746 @3x
Language:  en-us
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2Fevents%2Fand8-fitness-dance-cardio-class%2F&os=iOS&os_version=14.6&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #359](https://deploy-preview-359--dcdesignweek.netlify.app/events/and8-fitness-dance-cardio-class/)

**Comment by marcusrelacion** [comment]
@yxxko this has been fixed.
