### ISSUE TITLE
Disco Dan sponsor header not filling into the shape

### ISSUE THREAD

**Issue by yxxko** [AIGAdc/dcdesignweek.org#410]
![image](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTRiNDc5ZjMtZWM2YS00ZDBiLWI5NGUtNmZlZmUzMzc4NWUzIiwiZGVwbG95X2lkIjoiNjExYzVmNjUyZThhNmIwMDA4ZGI0NDgwIiwiaWQiOiI0MTI5MjI1Yi02ZjcwLTRkODQtODc0YS0wYWY0NmIxN2NhYjcifQ==)

```
Path:      /about/
Browser:   Mobile Safari 14.1.1 on iOS 14.6
Viewport:  428 x 746 @3x
Language:  en-us
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2Fabout%2F&os=iOS&os_version=14.6&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #359](https://deploy-preview-359--dcdesignweek.netlify.app/about/)

**Comment by marcusrelacion** [comment]
@yxxko this has been fixed.
