### ISSUE TITLE
Header Inconsistencies

### ISSUE THREAD

**Issue by silviascript** [AIGAdc/dcdesignweek.org#411]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTRiNDc5ZjMtZWM2YS00ZDBiLWI5NGUtNmZlZmUzMzc4NWUzIiwiZGVwbG95X2lkIjoiNjExYzVmNjUyZThhNmIwMDA4ZGI0NDgwIiwiaWQiOiJkMzliMWEzNi1mNTE3LTQ4NTctYTljMi1iNGNlOWRhMzIzZGMifQ==)

The header for the page is visually inconsistent from the About and Makers pages. Use the same font-size from the Makers page.

```
Path:      /about/
Browser:   Chrome 92.0.4515.159 on Mac OS 10.15.7
Viewport:  1920 x 1096 @1x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2Fabout%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=92.0&resolution=1920x1096&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #359](https://deploy-preview-359--dcdesignweek.netlify.app/about/)

**Comment by marcusrelacion** [comment]
@silviascript this has been fixed.
