### ISSUE TITLE
Disco Dan sponsor title not fitting the shape

### ISSUE THREAD

**Issue by yxxko** [AIGAdc/dcdesignweek.org#416]
![image](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTRiNDc5ZjMtZWM2YS00ZDBiLWI5NGUtNmZlZmUzMzc4NWUzIiwiZGVwbG95X2lkIjoiNjExZGE3N2M5OTFjODQwMDA3MmE2NTEzIiwiaWQiOiI3ZjU0ZTJjZS1jZTcwLTQyYzYtOGU3Ni1mOWQwYjY4ZTFjNjUifQ==)

😩😩

```
Path:      /about/#sponsors
Browser:   Mobile Safari 14.1.1 on iOS 14.6
Viewport:  428 x 860 @3x
Language:  en-us
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2Fabout%2F%23sponsors&os=iOS&os_version=14.6&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #359](https://deploy-preview-359--dcdesignweek.netlify.app/about/#sponsors)

**Comment by marcusrelacion** [comment]
@yxxko this has been fixed.
