### ISSUE TITLE
Skip to main should skip to the `h1` on the page

### ISSUE THREAD

**Issue by joshkimux** [AIGAdc/dcdesignweek.org#421]
[uploading...]

### Description of issue
Using the skip to main jumps focus to the `h2` on the homepage.

### Expected result
Skip to main should jump to the `h1` within the `main` element.

### Steps to reproduce
1. On the homepage, turn on Voiceover on Safari
2. Tab to the skip to main link and activate it with `ctrl` `opt` `space`
3. Confirm that it jumps to the `h2`, not the `h1`

```
Path:      /#skip-to-content
Browser:   Chrome 92.0.4515.131 on Mac OS 10.15.7
Viewport:  1277 x 1009 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2F%23skip-to-content&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=92.0&resolution=1277x1009&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #359](https://deploy-preview-359--dcdesignweek.netlify.app/#skip-to-content)

**Comment by marcusrelacion** [comment]
@joshkimux this has been fixed.
