### ISSUE TITLE
Black paper is overlapping sticker

### ISSUE THREAD

**Issue by yxxko** [AIGAdc/dcdesignweek.org#424]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTRiNDc5ZjMtZWM2YS00ZDBiLWI5NGUtNmZlZmUzMzc4NWUzIiwiZGVwbG95X2lkIjoiNjExZTkzYmNiZjBmNDkwMDA3MWY0OTVkIiwiaWQiOiIxZjA1MWZmOS03NWNhLTRiY2MtYTI2My0yN2YwNTYwNzUwMjIifQ==)

```
Path:      /about/
Browser:   Chrome 92.0.4515.131 on Mac OS 10.15.7
Viewport:  1792 x 927 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-419--dcdesignweek.netlify.app%2Fabout%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=92.0&resolution=1792x927&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #419](https://deploy-preview-419--dcdesignweek.netlify.app/about/)

**Comment by marcusrelacion** [comment]
@yxxko this has been fixed.
